# This is a config file for TF training
# Using YAML syntax

# Recording YAML Version, For upgrading
version: 0.1

# Define max atom number to be trained
max_atom_num: 25

# Define the structure file
str_file: "./TrainStr.txt"
# Define the force file
force_file: "./TrainFor.txt"

# Ouput Train file
train_file: "./train.tfrecords"
val_file: "./val.tfrecords"
test_file: "./test.tfrecords"

# For data splitting
train_prob: 0.9
val_prob: 0.05
test_prob: 0.05

# This section define the atom name and
# serial number of each species
atoms:
    C: 6
    O: 8
    N: 7
    H: 1

# Map Embeddings:
embeds:
    C: 0
    O: 1
    N: 2
    H: 3
